import React from 'react';

const CourseTypeSelect = ({value, onChange}) => {
  return (
  <select value={value} label={value} onChange={onChange} style={{width:'100%', height:'100%'}}>
    <option value="">Course Type</option>
    <option value="ABROD">Abroad, Study Term (ABROD)</option>
    <option value="ACCTG">Accounting (ACCTG)</option>
    <option value="AGRMT">Agreement Formal (Registration) (AGRMT)</option>
    <option value="AREC">Agricultural and Resource Economics (AREC)</option>
    <option value="AFNS">Agricultural, Food and Nutritional Science (AFNS)</option>
    <option value="ALES">Agricultural, Life and Environmental Sciences (ALES)</option>
    <option value="ASL">American Sign Language (ASL)</option>
    <option value="ANAT">Anatomy (ANAT)</option>
    <option value="AN SC">Animal Science (AN SC)</option>
    <option value="ANTHR">Anthropology (ANTHR)</option>
    <option value="ARAB">Arabic (ARAB)</option>
    <option value="ART">Art (ART)</option>
    <option value="ASTRO">Astronomy (ASTRO)</option>
    <option value="AUACC">Augustana Faculty - Accounting (AUACC)</option>
    <option value="AUART">Augustana Faculty - Art (AUART)</option>
    <option value="AUBIO">Augustana Faculty - Biology (AUBIO)</option>
    <option value="AUCHE">Augustana Faculty - Chemistry (AUCHE)</option>
    <option value="AUCLA">Augustana Faculty - Classical Studies (AUCLA)</option>
    <option value="AUCSL">Augustana Faculty - Community Service Learning (AUCSL)</option>
    <option value="AUCSC">Augustana Faculty - Computing Science (AUCSC)</option>
    <option value="AUCRI">Augustana Faculty - Crime and Community (AUCRI)</option>
    <option value="AUDRA">Augustana Faculty - Drama (AUDRA)</option>
    <option value="AUECO">Augustana Faculty - Economics (AUECO)</option>
    <option value="AUEFX">Augustana Faculty - Education Field Experience (AUEFX)</option>
    <option value="AUEPS">Augustana Faculty - Educational Psychology (AUEPS)</option>
    <option value="AUENG">Augustana Faculty - English (AUENG)</option>
    <option value="AUENV">Augustana Faculty - Environmental Studies (AUENV)</option>
    <option value="AUFAR">Augustana Faculty - Fine Arts (AUFAR)</option>
    <option value="AUFRE">Augustana Faculty - French (AUFRE)</option>
    <option value="AUGEO">Augustana Faculty - Geography (AUGEO)</option>
    <option value="AUGER">Augustana Faculty - German (AUGER)</option>
    <option value="AUGDS">Augustana Faculty - Global and Development Studies (AUGDS)</option>
    <option value="AUHIS">Augustana Faculty - History (AUHIS)</option>
    <option value="AUIND">Augustana Faculty - Indigenous Studies (AUIND)</option>
    <option value="AUIDS">Augustana Faculty - Interdisciplinary Studies (AUIDS)</option>
    <option value="AULAN">Augustana Faculty - Language Studies (AULAN)</option>
    <option value="AUMGT">Augustana Faculty - Management (AUMGT)</option>
    <option value="AUMAT">Augustana Faculty - Mathematics (AUMAT)</option>
    <option value="AUMUS">Augustana Faculty - Music (AUMUS)</option>
    <option value="AUPHI">Augustana Faculty - Philosophy (AUPHI)</option>
    <option value="AUPAC">Augustana Faculty - Physical Activity (AUPAC)</option>
    <option value="AUPED">Augustana Faculty - Physical Education (AUPED)</option>
    <option value="AUPHY">Augustana Faculty - Physics (AUPHY)</option>
    <option value="AUPOL">Augustana Faculty - Political Studies (AUPOL)</option>
    <option value="AUPSY">Augustana Faculty - Psychology (AUPSY)</option>
    <option value="AUREL">Augustana Faculty - Religion (AUREL)</option>
    <option value="AUSCA">Augustana Faculty - Scandinavian (AUSCA)</option>
    <option value="AUSOC">Augustana Faculty - Sociology (AUSOC)</option>
    <option value="AUSPA">Augustana Faculty - Spanish (AUSPA)</option>
    <option value="AUSTA">Augustana Faculty - Statistics (AUSTA)</option>
    <option value="BIOCH">Biochemistry (BIOCH)</option>
    <option value="BIOIN">Bioinformatics (BIOIN)</option>
    <option value="BIOL">Biology (BIOL)</option>
    <option value="BME">Biomedical Engineering (BME)</option>
    <option value="BOT">Botany (BOT)</option>
    <option value="BUS">Business (BUS)</option>
    <option value="BUEC">Business Economics (BUEC)</option>
    <option value="B LAW">Business Law (B LAW)</option>
    <option value="TAAFI">CCA - Finance (TAAFI)</option>
    <option value="GTOTC">CCA - Gestion touristique (GTOTC)</option>
    <option value="TAAMG">CCA - Management (TAAMG)</option>
    <option value="PSSTC">CCA - Préposé aux soins de santé (PSSTC)</option>
    <option value="TAARH">CCA - Ressources humaines (TAARH)</option>
    <option value="TAATC">CCA - Tronc commun (TAATC)</option>
    <option value="CELL">Cell Biology (CELL)</option>
    <option value="CH E">Chemical Engineering (CH E)</option>
    <option value="CME">Chemical and Materials Engineering (CME)</option>
    <option value="CHEM">Chemistry (CHEM)</option>
    <option value="CHINA">Chinese (CHINA)</option>
    <option value="CHRTC">Christian Theology at St Joseph's College (CHRTC)</option>
    <option value="CHRTP">Christian Theology at St Stephen's College (CHRTP)</option>
    <option value="CIV E">Civil Engineering (CIV E)</option>
    <option value="CLASS">Classics (CLASS)</option>
    <option value="CSD">Communication Sciences and Disorders (CSD)</option>
    <option value="COMM">Communications and Technology (COMM)</option>
    <option value="MACE">Community Engagement (MACE)</option>
    <option value="CSL">Community Service-Learning (CSL)</option>
    <option value="C LIT">Comparative Literature (C LIT)</option>
    <option value="CMPUT">Computing Science (CMPUT)</option>
    <option value="DANCE">Dance (DANCE)</option>
    <option value="DAC">Dance Activity (DAC)</option>
    <option value="D HYG">Dental Hygiene (D HYG)</option>
    <option value="DDS">Dentistry (DDS)</option>
    <option value="DENT">Dentistry (DENT)</option>
    <option value="DMED">Dentistry/Medicine (DMED)</option>
    <option value="DES">Design (DES)</option>
    <option value="DRAMA">Drama (DRAMA)</option>
    <option value="EAS">Earth and Atmospheric Sciences (EAS)</option>
    <option value="EASIA">East Asian Studies (EASIA)</option>
    <option value="ECON">Economics (ECON)</option>
    <option value="EDU">Education (EDU)</option>
    <option value="EDCT">Education - Career Technology Studies (EDCT)</option>
    <option value="EDEL">Education - Elementary (EDEL)</option>
    <option value="EDES">Education - Elementary and Secondary (EDES)</option>
    <option value="EDFX">Education - Field Experience (EDFX)</option>
    <option value="EDIT">Education - Instructional Technology (EDIT)</option>
    <option value="EDPS">Education - Policy Studies (EDPS)</option>
    <option value="EDPY">Education - Psychology (EDPY)</option>
    <option value="EDSE">Education - Secondary (EDSE)</option>
    <option value="ECE">Electrical and Computer Engineering (ECE)</option>
    <option value="ENG M">Engineering Management (ENG M)</option>
    <option value="EN PH">Engineering Physics (EN PH)</option>
    <option value="ENCMP">Engineering, Computer (ENCMP)</option>
    <option value="ENGG">Engineering, General (ENGG)</option>
    <option value="ENGL">English (ENGL)</option>
    <option value="EAP">English for Academic Purposes (EAP)</option>
    <option value="ENT">Entomology (ENT)</option>
    <option value="ENV E">Environmental Engineering (ENV E)</option>
    <option value="ENCS">Environmental and Conservation Sciences (ENCS)</option>
    <option value="EXCH">Exchange Program (EXCH)</option>
    <option value="EXT">Extension (EXT)</option>
    <option value="ADMI">FSJ - Administration (ADMI)</option>
    <option value="ANATE">FSJ - Anatomie (ANATE)</option>
    <option value="ANGL">FSJ - Anglais (ANGL)</option>
    <option value="ALS">FSJ - Anglais langue seconde (ALS)</option>
    <option value="ANTHE">FSJ - Anthropologie (ANTHE)</option>
    <option value="ADRAM">FSJ - Art dramatique (ADRAM)</option>
    <option value="BIOCM">FSJ - Biochimie (BIOCM)</option>
    <option value="BIOLE">FSJ - Biologie (BIOLE)</option>
    <option value="CHIM">FSJ - Chimie (CHIM)</option>
    <option value="ECONE">FSJ - Economie (ECONE)</option>
    <option value="EDU F">FSJ - Education - Fondements (EDU F)</option>
    <option value="EDU M">FSJ - Education - Methodologie et Curriculum (EDU M)</option>
    <option value="EDU P">FSJ - Education - Psychologie (EDU P)</option>
    <option value="EDU S">FSJ - Education - Stage (EDU S)</option>
    <option value="ETCAN">FSJ - Etudes canadiennes (ETCAN)</option>
    <option value="FRANC">FSJ - Français (FRANC)</option>
    <option value="HISTE">FSJ - Histoire (HISTE)</option>
    <option value="HUME">FSJ - Humanités (HUME)</option>
    <option value="LINGQ">FSJ - Linguistique (LINGQ)</option>
    <option value="MATHQ">FSJ - Mathématiques (MATHQ)</option>
    <option value="M EDU">FSJ - Maîtrise ès sciences de l'éducation (M EDU)</option>
    <option value="MICRE">FSJ - Microbiologie (MICRE)</option>
    <option value="MUSIQ">FSJ - Musique (MUSIQ)</option>
    <option value="PHILE">FSJ - Philosophie (PHILE)</option>
    <option value="PHYSE">FSJ - Physiologie (PHYSE)</option>
    <option value="PHYSQ">FSJ - Physique (PHYSQ)</option>
    <option value="PSYCE">FSJ - Psychologie (PSYCE)</option>
    <option value="SC PO">FSJ - Science politique (SC PO)</option>
    <option value="SCSOC">FSJ - Sciences sociales (SCSOC)</option>
    <option value="SOCIE">FSJ - Sociologie (SOCIE)</option>
    <option value="F MED">Family Medicine (F MED)</option>
    <option value="FS">Film Studies (FS)</option>
    <option value="FIN">Finance (FIN)</option>
    <option value="FOREC">Forest Economics (FOREC)</option>
    <option value="FREN">French Language and Literature (FREN)</option>
    <option value="GSJ">Gender and Social Justice (GSJ)</option>
    <option value="GENET">Genetics (GENET)</option>
    <option value="GEOPH">Geophysics (GEOPH)</option>
    <option value="GERM">German (GERM)</option>
    <option value="GREEK">Greek (GREEK)</option>
    <option value="HE ED">Health Education (HE ED)</option>
    <option value="HIST">History (HIST)</option>
    <option value="HADVC">History of Art, Design, and Visual Culture (HADVC)</option>
    <option value="HECOL">Human Ecology (HECOL)</option>
    <option value="HGP">Human Geography and Planning (HGP)</option>
    <option value="HUCO">Humanities Computing (HUCO)</option>
    <option value="IMIN">Immunology and Infection (IMIN)</option>
    <option value="IPG">Integrated Petroleum Geosciences (IPG)</option>
    <option value="INT D">Interdisciplinary Undergraduate &amp; Graduate Courses (INT D)</option>
    <option value="ITAL">Italian (ITAL)</option>
    <option value="JAPAN">Japanese (JAPAN)</option>
    <option value="KIN">Kinesiology (KIN)</option>
    <option value="KRLS">Kinesiology, Recreation, Leisure and Sport (KRLS)</option>
    <option value="KOREA">Korean (KOREA)</option>
    <option value="LABMP">Laboratory Medicine and Pathology (LABMP)</option>
    <option value="LATIN">Latin (LATIN)</option>
    <option value="LA ST">Latin American Studies (LA ST)</option>
    <option value="LAW">Law (LAW)</option>
    <option value="LIS">Library and Information Studies (LIS)</option>
    <option value="LING">Linguistics (LING)</option>
    <option value="M REG">Maintaining Registration (M REG)</option>
    <option value="MIS">Management Information Systems (MIS)</option>
    <option value="MGTSC">Management Science (MGTSC)</option>
    <option value="MA SC">Marine Science (MA SC)</option>
    <option value="MARK">Marketing (MARK)</option>
    <option value="MINT">Master of Internetworking (MINT)</option>
    <option value="MAT E">Materials Engineering (MAT E)</option>
    <option value="MA PH">Mathematical Physics (MA PH)</option>
    <option value="MATH">Mathematics (MATH)</option>
    <option value="MEC E">Mechanical Engineering (MEC E)</option>
    <option value="MDGEN">Medical Genetics (MDGEN)</option>
    <option value="MLSCI">Medical Laboratory Science (MLSCI)</option>
    <option value="MMI">Medical Microbiology and Immunology (MMI)</option>
    <option value="MED">Medicine (MED)</option>
    <option value="MICRB">Microbiology (MICRB)</option>
    <option value="MIN E">Mining Engineering (MIN E)</option>
    <option value="MLCS">Modern Languages and Cultural Studies (MLCS)</option>
    <option value="MM">Multimedia (MM)</option>
    <option value="MUSIC">Music (MUSIC)</option>
    <option value="NS">Native Studies (NS)</option>
    <option value="NEURO">Neuroscience and Mental Health Institute (NEURO)</option>
    <option value="NORW">Norwegian (NORW)</option>
    <option value="NURS">Nursing (NURS)</option>
    <option value="NUTR">Nutrition (NUTR)</option>
    <option value="NU FS">Nutrition and Food Sciences (NU FS)</option>
    <option value="OB GY">Obstetrics and Gynaecology (OB GY)</option>
    <option value="OCCTH">Occupational Therapy (OCCTH)</option>
    <option value="ONCOL">Oncology (ONCOL)</option>
    <option value="OM">Operations Management (OM)</option>
    <option value="OPHTH">Ophthalmology (OPHTH)</option>
    <option value="OBIOL">Oral Biology (OBIOL)</option>
    <option value="PAED">Paediatrics (PAED)</option>
    <option value="PALEO">Paleontology (PALEO)</option>
    <option value="PET E">Petroleum Engineering (PET E)</option>
    <option value="PMCOL">Pharmacology (PMCOL)</option>
    <option value="PHARM">Pharmacy (PHARM)</option>
    <option value="PHIL">Philosophy (PHIL)</option>
    <option value="PAC">Physical Activity (PAC)</option>
    <option value="PTHER">Physical Therapy (PTHER)</option>
    <option value="PHYS">Physics (PHYS)</option>
    <option value="PHYSL">Physiology (PHYSL)</option>
    <option value="PL SC">Plant Science (PL SC)</option>
    <option value="POLSH">Polish (POLSH)</option>
    <option value="POL S">Political Science (POL S)</option>
    <option value="PSYCI">Psychiatry (PSYCI)</option>
    <option value="PSYCO">Psychology (PSYCO)</option>
    <option value="RADTH">Radiation Therapy (RADTH)</option>
    <option value="RADDI">Radiology and Diagnostic Imaging (RADDI)</option>
    <option value="RLS">Recreation and Leisure Studies (RLS)</option>
    <option value="REHAB">Rehabilitation Medicine (REHAB)</option>
    <option value="RELIG">Religious Studies (RELIG)</option>
    <option value="REN R">Renewable Resources (REN R)</option>
    <option value="RSCH">Research (RSCH)</option>
    <option value="R SOC">Rural Sociology (R SOC)</option>
    <option value="RUSS">Russian (RUSS)</option>
    <option value="SCAND">Scandinavian (SCAND)</option>
    <option value="SPH">School of Public Health (SPH)</option>
    <option value="SCI">Science (SCI)</option>
    <option value="STS">Science, Technology, and Society (STS)</option>
    <option value="SC INF">Sciences infirmières (SC INF)</option>
    <option value="SLAV">Slavic and East European Studies (SLAV)</option>
    <option value="SOC">Sociology (SOC)</option>
    <option value="SPAN">Spanish (SPAN)</option>
    <option value="STAT">Statistics (STAT)</option>
    <option value="SMO">Strategic Management and Organization (SMO)</option>
    <option value="SURG">Surgery (SURG)</option>
    <option value="SWED">Swedish (SWED)</option>
    <option value="T DES">Theatre Design (T DES)</option>
    <option value="THES">Thesis (THES)</option>
    <option value="UKR">Ukrainian (UKR)</option>
    <option value="UNIV">University (UNIV)</option>
    <option value="PLAN">Urban and Regional Planning (PLAN)</option>
    <option value="WGS">Women's and Gender Studies (WGS)</option>
    <option value="WKEXP">Work Experience (WKEXP)</option>
    <option value="WRITE">Write (Creative Writing) (WRITE)</option>
    <option value="WRS">Writing Studies (WRS)</option>
    <option value="ZOOL">Zoology (ZOOL)</option>
  </select>

  );
}

export default CourseTypeSelect;
